server:
  port : 8081
spring:
  profiles:
    active: development
  
  # Security configuration
  #security:
   # user:
    #  name: user
     # password: user
  # Database
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=RECHARGE_DB
    username: sa
    password: Heritage@12
  # JPA properties
  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    open-in-view: false
    #generate-ddl: true
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
